Repository Capstone-Alterra/react-raih-peduli, pull requests merged in 2023-12, with the labels that each got.

#41 Bugfix/validation schema in fundraise page
  package-lock.json
  package.json
  src/components/breadcrumbs.jsx
  src/components/input-file.jsx
  src/components/ui/alert-dialog.jsx
  src/components/ui/dialog.jsx
  src/pages/fundraising/components/alert-dialog.jsx
  src/pages/fundraising/components/form.jsx
  src/pages/fundraising/components/fundraise-columns.jsx
  src/pages/fundraising/components/response-dialogue.jsx
  src/utils/api/auth/api.js
  src/utils/api/fundraise/api.js
  src/utils/api/fundraise/index.js
  src/utils/api/fundraise/schema.js
Labels: bug, enhancement

#53 Fix: Resolved validation Issue
  src/components/input-file.jsx
  src/pages/fundraising/components/form.jsx
  src/utils/api/fundraise/schema.js
Labels: bug

#54 Fix: Validation schema
  src/pages/news/components/form.jsx
  src/pages/news/components/news-columns.jsx
  src/utils/api/fundraise/schema.js
  src/utils/api/news/api.js
  src/utils/api/news/schema.js
Labels: bug

#55 Feat: Implement generate content with AI
  src/components/custom-textarea.jsx
  src/components/input-file.jsx
  src/pages/news/components/ai-dialog.jsx
  src/pages/news/components/form.jsx
  src/pages/news/components/news-table.jsx
  src/pages/news/index.jsx
  src/utils/api/news/api.js
Labels: enhancement

#56 Feat: Integration Transaction Page
  src/pages/transaction/.gitkeep
  src/pages/transaction/MOCK_DATA.json
  src/pages/transaction/columns.jsx
  src/pages/transaction/components/form-header.jsx
  src/pages/transaction/components/form-layout.jsx
  src/pages/transaction/components/form.jsx
  src/pages/transaction/components/skeleton/skeleton-form.jsx
  src/pages/transaction/components/skeleton/skeleton-table.jsx
  src/pages/transaction/components/status-badge.jsx
  src/pages/transaction/components/transaction-columns.jsx
  src/pages/transaction/components/transaction-table.jsx
  src/pages/transaction/detail-transaction.jsx
  src/pages/transaction/index.jsx
  src/pages/transaction/transaction-detail.jsx
  src/routes/index.jsx
  src/utils/api/transaction/api.js
  src/utils/api/transaction/index.js
Labels: enhancement

#60 Feat&Bugfix: Implement search user and fix validation issue
  src/pages/customer/components/customer-table.jsx
  src/pages/customer/components/form.jsx
  src/pages/customer/index.jsx
  src/utils/api/customer/api.js
  src/utils/api/customer/schema.js
Labels: bug, enhancement

#61 Feat: Integration volunteer vacancy page
  src/assets/icons/approve.jsx
  src/components/breadcrumbs.jsx
  src/components/form/form-layout.jsx
  src/components/layout.jsx
  src/components/multiple-select.jsx
  src/components/single-select.jsx
  src/components/ui/select.jsx
  src/pages/dashboard/index.jsx
  src/pages/list-registered/components/form.jsx
  src/pages/list-registered/components/registrant-column.jsx
  src/pages/list-registered/components/registrant-table.jsx
  src/pages/list-registered/components/response-dialog.jsx
  src/pages/list-registered/components/skeleton/skeleton-form.jsx
  src/pages/list-registered/components/skeleton/skeleton-table.jsx
  src/pages/list-registered/detail-registrant.jsx
  src/pages/list-registered/index.jsx
  src/pages/volunter/MOCK_DATA.json
  src/pages/volunter/add-volunteer-vacancies.jsx
  src/pages/volunter/columns.jsx
  src/pages/volunter/components/delete-dialog.jsx
  src/pages/volunter/components/form-header.jsx
  src/pages/volunter/components/form.jsx
  src/pages/volunter/components/response-dialogue.jsx
  src/pages/volunter/components/skeletons/skeleton-form.jsx
  src/pages/volunter/components/skeletons/skeleton-table.jsx
  src/pages/volunter/components/volunter-columns.jsx
  src/pages/volunter/components/volunter-table.jsx
  src/pages/volunter/detail-volunteer-vacancies.jsx
  src/pages/volunter/detail.jsx
  src/pages/volunter/form.jsx
  src/pages/volunter/index.jsx
  src/pages/volunter/list-registered/MOCK_LIST_DATA.json
  src/pages/volunter/list-registered/list-columns.jsx
  src/pages/volunter/list-registered/list-volunter.jsx
  src/pages/volunter/response-form.jsx
  src/routes/index.jsx
  src/utils/api/auth/api.js
  src/utils/api/axiosWithConfig.js
  src/utils/api/volunter/api.js
  src/utils/api/volunter/index.js
  src/utils/api/volunter/schema.js
Labels: enhancement

#62 Forget password
  src/pages/login/forgot-password/ForgotPasswordPage.jsx
  src/pages/login/forgot-password/OTPPage.jsx
  src/pages/login/forgot-password/RePasswordPage.jsx
  src/pages/login/forgot-password/RepasswordSuccess.jsx
  src/routes/index.jsx
  src/routes/protected-routes.jsx
  src/utils/api/auth/api.js
  src/utils/api/auth/forget-password/api.js
  src/utils/api/auth/forget-password/index.js
  src/utils/api/auth/forget-password/type.js
  src/utils/api/auth/type.js
  src/utils/context/token.jsx
  src/utils/setAxiosWithConfig.js
Labels: enhancement

#64 Fix: Volunteer vacancy page
  src/pages/list-registered/components/form.jsx
  src/pages/volunter/components/form.jsx
  src/utils/api/volunter/index.js
  src/utils/api/volunter/schema.js
Labels: bug

#66 Feat: Implement Token Refresh and Display Dynamic Full Name from API
  package-lock.json
  package.json
  src/components/navbar.jsx
  src/pages/login/.gitkeep
  src/pages/login/index.jsx
  src/routes/index.jsx
  src/routes/protected-routes.jsx
  src/utils/api/auth/api.js
  src/utils/api/auth/forget-password/api.js
  src/utils/api/auth/forget-password/index.js
  src/utils/api/auth/forget-password/schema.js
  src/utils/api/auth/forget-password/type.js
  src/utils/api/auth/index.js
  src/utils/api/auth/schema.js
  src/utils/api/auth/type.js
  src/utils/api/axiosWithConfig.js
  src/utils/api/fundraise/api.js
  src/utils/context/token.jsx
  src/utils/setAxiosWithConfig.js
Labels: enhancement

#67 Feat: Implement export fundraise data
  package-lock.json
  package.json
  src/pages/fundraising/index.jsx
Labels: enhancement

#70 Improvement: Truncate long description and fix fullname not diplayed correctly
  src/components/navbar.jsx
  src/pages/dashboard/components/fundraise-column.jsx
  src/pages/dashboard/components/volunteer-column.jsx
  src/pages/fundraising/components/fundraise-columns.jsx
  src/pages/news/components/news-columns.jsx
  src/pages/transaction/components/form.jsx
  src/pages/volunter/components/volunter-columns.jsx
  src/utils/api/customer/schema.js
  src/utils/api/fundraise/schema.js
  src/utils/api/news/schema.js
  src/utils/context/token.jsx
Labels: enhancement

#73 Fix forgot-password
  src/pages/login/forgot-password/ForgotPasswordPage.jsx
  src/pages/login/forgot-password/OTPPage.jsx
  src/utils/api/auth/forget-password/schema.js
Labels: enhancement
